### ISSUE TITLE
Issues on 1.19

### ISSUE THREAD

**Issue by ultraic-space** [EvModder/PeacefulPetHeads#1]
Hi! This extension looks great, but I seem to be getting some errors on installing it in 1.19.
https://www.toptal.com/developers/hastebin/sizuvefase.properties
Mob heads and player heads do seem to drop from the main plugin.
![image](https://user-images.githubusercontent.com/108235651/175828210-ffb36a23-8774-4b1a-9123-46387d114341.png)

**Comment by EvModder** [comment]
(sorry for not replying to this thread publicly - this was solved offline with 1.2 a few years ago) just remembering to close it now
